### ISSUE TITLE
31st February issue

### ISSUE THREAD

**Issue by sauravexodus** [chenglei1986/DatePicker#1]
This is generated when user goes to date 31st March/January and then changes month back to February.

**Comment by sauravexodus** [comment]
This can be fixed by clearing the Gregorian Calendar object before changing dates.

**Comment by chenglei1986** [comment]
@sauravexodus Thanks for your reminding! I've fixed it at [38b37e4](https://github.com/chenglei1986/DatePicker/commit/38b37e4ae22e982e5c8af0b0eb023af18a4b5a13).
