### ISSUE TITLE
年月日可以改成和具体的数字在一条直线上吗

### ISSUE THREAD

**Issue by jeffreyzhang23** [chenglei1986/DatePicker#4]
年月日可以改成和具体的数字在一条直线上吗 @chenglei1986

**Comment by chenglei1986** [comment]
你需要的可能是这个[WheelPicker](https://github.com/AigeStudio/WheelPicker)或[Android-PickerView](https://github.com/Bigkoo/Android-PickerView)

**Comment by jeffreyzhang23** [comment]
OK，谢谢你
